"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowDown, Plus, Minus, Download, Pause, Play } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";

const projects = [
 { id: "01", name: "Solenne", category: "MULTIMODAL AI / WELLNESS", date: "FEATURED PROJECT · PROTOTYPE", headline: "A moment to reflect.\nA system to understand.", description: "A private video-journaling prototype that turns speech, voice, and visual signals into transcripts and gentle reflection prompts.", tags: ["Flutter", "Python", "Firestore", "Whisper"], steps: ["Record a private video journal", "Queue background analysis", "Combine speech, voice & visuals", "Receive live reflection insights"], detail: "Built a Flutter journaling client with Riverpod and Firebase authentication, Cloudinary media uploads, and live Firestore updates. A Python worker processes queued journals using faster-whisper transcription, MediaPipe and OpenCV visual analysis, librosa voice features, and text sentiment. Optional Groq-generated reflection cards can use a human-approved research catalog. Designed for non-clinical self-reflection, not diagnosis or treatment.", stack: "Flutter · Dart · Riverpod · Firebase · Cloudinary · Python · Docker · faster-whisper · MediaPipe · OpenCV · librosa · Groq", color: "violet" },
 { id: "02", name: "CortexEdu", category: "EDTECH / MOBILE ENGINEERING", date: "JAN — JUN 2026", headline: "Less admin.\nMore learning.", description: "Bringing the classroom together. A mobile application connecting interactive classes, attendance, assessment, and student engagement.", tags: ["Flutter", "Dart", "Firebase", "Node.js"], steps: ["Join an interactive class", "Check in with a QR code", "Track assessment performance", "Earn participation rewards"], detail: "Built real-time interactive classes and QR-based attendance, alongside automated Continuous Internal Assessment calculations. Performance dashboards support students and faculty, while a token reward system encourages participation.", stack: "Flutter · Dart · Firebase · Node.js · Provider · Cloudinary", color: "lime" },
 { id: "03", name: "DoChain", category: "WEB3 / FULL-STACK ENGINEERING", date: "AUG — OCT 2025", headline: "Documents.\nWith a chain of trust.", description: "A decentralized application for secure, transparent document transactions. From wallet authentication to distributed storage.", tags: ["Next.js", "Solidity", "IPFS", "Polygon"], steps: ["Connect a MetaMask wallet", "Store documents with IPFS", "Interact with a smart contract", "Record on Polygon testnet"], detail: "Designed a decentralized document transaction application with Solidity smart contracts and MetaMask wallet authentication. IPFS and Pinata handle decentralized file storage; contracts were deployed on the Polygon test network.", stack: "Next.js · Solidity · Hardhat · MetaMask · IPFS · Polygon · Prisma · Pinata", color: "blue" },
 { id: "04", name: "AI Fitness", category: "GENERATIVE AI / WEB DEVELOPMENT", date: "JUL — AUG 2025", headline: "Personal goals.\nIntelligent plans.", description: "Turning individual fitness goals and physical attributes into personalized workout plans through generative AI.", tags: ["Next.js", "Gemini API", "MongoDB", "Tailwind CSS"], steps: ["Define personal fitness goals", "Provide physical attributes", "Generate a tailored routine", "Explore the workout plan"], detail: "Built a responsive fitness platform integrating Google’s Gemini API to generate personalized workout routines based on user goals and physical attributes. Tailwind CSS powers the interface, with MongoDB managing user information.", stack: "Next.js · Tailwind CSS · MongoDB · Gemini API", color: "orange" },
];
function ParticleField({ paused }: { paused: boolean }) {
 const ref = useRef<HTMLCanvasElement>(null);
 useEffect(() => {
  const canvas = ref.current; if (!canvas) return;
  const ctx = canvas.getContext("2d"); if (!ctx) return;
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)");
  let width = 0, height = 0, frame = 0, angle = 0, visible = true;
  const pointer = { x: 0, y: 0 };
  const points = Array.from({ length: 580 }, (_, i) => { const phi = Math.acos(1 - 2 * (i + 0.5) / 580), theta = Math.PI * (1 + Math.sqrt(5)) * i; return { x: Math.cos(theta) * Math.sin(phi), y: Math.sin(theta) * Math.sin(phi), z: Math.cos(phi) }; });
  const resize = () => { const r = canvas.getBoundingClientRect(); width = r.width; height = r.height; const dpr = Math.min(devicePixelRatio, 2); canvas.width = width * dpr; canvas.height = height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); };
  const move = (e: PointerEvent) => { const r = canvas.getBoundingClientRect(); pointer.x = (e.clientX - r.left) / r.width - 0.5; pointer.y = (e.clientY - r.top) / r.height - 0.5; };
  const leave = () => { pointer.x = 0; pointer.y = 0; };
  const draw = () => {
   if (visible) { ctx.clearRect(0, 0, width, height); const radius = Math.min(width, height) * 0.35; const rotation = angle + pointer.x * 0.7;
    const projected = points.map(p => { const x = p.x * Math.cos(rotation) - p.z * Math.sin(rotation); const z = p.x * Math.sin(rotation) + p.z * Math.cos(rotation); const y = p.y * Math.cos(pointer.y) - z * Math.sin(pointer.y); const scale = 2.8 / (2.8 - z * 0.45); return { x: width / 2 + x * radius * scale, y: height / 2 + y * radius * scale, z }; });
    projected.forEach((p, i) => { ctx.fillStyle = `rgba(211,255,64,${0.2 + (p.z + 1) * 0.35})`; ctx.beginPath(); ctx.arc(p.x, p.y, p.z > 0.5 ? 2.1 : 1.2, 0, Math.PI * 2); ctx.fill(); const q = projected[(i + 21) % projected.length]; if (p.z > 0 && q.z > 0 && Math.hypot(p.x - q.x, p.y - q.y) < radius * 0.23) { ctx.strokeStyle = "rgba(211,255,64,.14)"; ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineTo(q.x, q.y); ctx.stroke(); } });
    if (!paused && !reduce.matches) angle += 0.0025;
   } if (!paused && !reduce.matches) frame = requestAnimationFrame(draw);
  };
  const observer = new ResizeObserver(() => { resize(); if (paused || reduce.matches) draw(); }); observer.observe(canvas);
  const intersection = new IntersectionObserver(entries => { visible = entries[0].isIntersecting; }); intersection.observe(canvas);
  resize(); draw(); canvas.addEventListener("pointermove", move); canvas.addEventListener("pointerleave", leave);
  return () => { cancelAnimationFrame(frame); observer.disconnect(); intersection.disconnect(); canvas.removeEventListener("pointermove", move); canvas.removeEventListener("pointerleave", leave); };
 }, [paused]);
 return <canvas ref={ref} className="particle-canvas" aria-hidden="true" />;
}
export default function Home() {
 const [paused, setPaused] = useState(false), [active, setActive] = useState(0), [detail, setDetail] = useState<number | null>(null), [menu, setMenu] = useState(false), [copied, setCopied] = useState(false);
 const root = useRef<HTMLElement>(null);
 useEffect(() => {
  const el = root.current; if (!el) return;
  const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add("revealed"); }), { threshold: 0.12 });
  el.querySelectorAll(".reveal").forEach(item => observer.observe(item)); let frame = 0;
  const update = () => { const max = document.documentElement.scrollHeight - innerHeight; el.style.setProperty("--progress", String(max > 0 ? scrollY / max : 0)); el.style.setProperty("--hero-shift", `${Math.min(scrollY * 0.17, 160)}px`); let current = 0; el.querySelectorAll<HTMLElement>(".project-chapter").forEach((chapter, i) => { if (chapter.getBoundingClientRect().top < innerHeight * 0.6) current = i; }); setActive(current); frame = 0; };
  const scroll = () => { if (!frame) frame = requestAnimationFrame(update); }; update(); addEventListener("scroll", scroll, { passive: true }); addEventListener("resize", scroll);
  return () => { observer.disconnect(); removeEventListener("scroll", scroll); removeEventListener("resize", scroll); cancelAnimationFrame(frame); };
 }, []);
 async function copyEmail() { try { await navigator.clipboard.writeText("Rajeev.chandar@mca.christuniversity.in"); setCopied(true); } catch { window.location.href = "mailto:Rajeev.chandar@mca.christuniversity.in"; } }
 return <main ref={root} className={paused ? "motion-paused" : ""}>
  <a className="skip-link" href="#about">Skip to content</a><div className="reading-progress" />
  <header className="nav"><a href="#home" className="monogram" aria-label="Rajeev Chandar home">rc<span>®</span></a><span className="nav-caption">RAJEEV CHANDAR<br />FULL-STACK DEVELOPER</span><nav aria-label="Main navigation" className={menu ? "nav-links open" : "nav-links"}>{[["Work", "work"], ["About", "about"], ["Experience", "experience"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a href="#contact" className="nav-contact" onClick={() => setMenu(false)}>Let’s talk <ArrowUpRight size={16} /></a></nav><button className="menu-toggle" aria-label={menu ? "Close navigation" : "Open navigation"} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <Minus /> : <Plus />}</button></header>
  <section id="home" className="hero"><div className="hero-top"><span>BASED IN BENGALURU, INDIA</span><span>CODE. CURIOSITY. CRAFT.</span></div><div className="hero-title"><h1><span>RAJEEV</span><span className="outline-word">CHANDAR<span className="title-star">✳</span></span></h1></div><div className="hero-orbit"><ParticleField paused={paused} /><div className="orbit-label"><span>INTERACTIVE SYSTEM / 001</span><span>MOVE TO EXPLORE</span></div></div><div className="hero-note"><span className="eyebrow">FULL-STACK DEVELOPER / MCA STUDENT</span><p>I turn complex problems<br />into experiences<br /><em>that just work.</em></p><a className="round-link" href="#work"><span>Explore my work</span><span className="circle"><ArrowDown size={22} /></span></a></div><div className="hero-bottom"><span>FROM IDEAS TO INTERFACES.</span><span className="scroll-hint">SCROLL TO DISCOVER <ArrowDown size={14} /></span><button className="motion-button" onClick={() => setPaused(!paused)} aria-pressed={paused}>{paused ? <Play size={13} /> : <Pause size={13} />} {paused ? "Motion paused" : "Motion on"}</button></div></section>
  <div className="ticker" aria-hidden="true"><div>CURIOUS BY NATURE <span>✳</span> ENGINEER BY CRAFT <span>✳</span> BUILT TO MAKE A DIFFERENCE <span>✳</span> CURIOUS BY NATURE <span>✳</span> ENGINEER BY CRAFT <span>✳</span></div></div>
  <section id="about" className="about section-pad"><div className="section-label"><span>01 / THE MINDSET</span><span>A LITTLE CONTEXT</span></div><div className="about-grid"><span className="small-cross" aria-hidden="true">✳</span><div><h2 className="reveal">Big curiosity.<br />Real-world <em>execution.</em></h2><div className="about-copy reveal"><p>I’m A R Rajeev Chandar, a full-stack developer pursuing my MCA at CHRIST University. I like working where thoughtful interfaces meet challenging engineering.</p><p>From learning content delivery at Adobe to building with AI, mobile, and blockchain, I bring an end-to-end mindset: understand the problem, build the system, refine the experience.</p></div><div className="quick-facts reveal"><div><strong>Adobe</strong><span>TECHNICAL CONSULTANT INTERN</span></div><div><strong>9.23<span>/10</span></strong><span>BCA CGPA · JAIN UNIVERSITY</span></div><div><strong>MCA ’27</strong><span>CHRIST UNIVERSITY</span></div></div></div></div></section>
  <section id="work" className="work"><div className="work-heading section-pad"><div className="section-label"><span>02 / SELECTED WORK</span><span>2025 — 2026</span></div><h2 className="reveal">Ideas into<br /><em>working reality.</em><sup>(04)</sup></h2><p>Four different challenges. One instinct to build.</p></div><div className="project-layout"><aside className={`project-stage stage-${projects[active].color}`}><div className="stage-top"><span>PROJECT ARCHITECTURE</span><span>{projects[active].id} / 04</span></div><div className="system-visual" key={active}><div className="system-core"><span>{active === 0 ? "S" : active === 1 ? "CE" : active === 2 ? "DC" : "AI"}</span><small>{active === 0 ? "SPACE TO REFLECT" : active === 1 ? "CLASSROOM, CONNECTED" : active === 2 ? "TRUST, DISTRIBUTED" : "FITNESS, PERSONALIZED"}</small></div><div className="system-path">{projects[active].steps.map((step, i) => <div key={step}><span>0{i + 1}</span>{step}<i /></div>)}</div></div><div className="stage-bottom"><span>CONCEPTUAL SYSTEM FLOW</span><div className="stage-dots">{projects.map((p, i) => <a key={p.id} href={`#project-${i}`} aria-label={`Jump to ${p.name}`} aria-current={active === i ? "step" : undefined} className={active === i ? "selected" : ""} />)}</div></div></aside><div className="project-chapters">{projects.map((project, i) => <article id={`project-${i}`} className={`project-chapter project-${project.color}`} key={project.id}><div className="chapter-meta"><span>{project.id} / {project.category}</span><span>{project.date}</span></div><div className="reveal"><h3>{project.name}</h3><h4>{project.headline}</h4><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><button className="project-button" onClick={() => setDetail(i)}>Inside the project <ArrowUpRight size={20} /></button></div><span className="chapter-watermark" aria-hidden="true">{project.id}</span></article>)}</div></div></section>
  <section id="experience" className="experience section-pad"><div className="section-label"><span>03 / EXPERIENCE & MOMENTUM</span><span>ALWAYS MOVING FORWARD</span></div><div className="experience-heading"><h2 className="reveal">Learning fast.<br /><em>Building further.</em></h2><a href="/Rajeev-Chandar-Resume.pdf" target="_blank" rel="noreferrer" className="text-link">Get my résumé <Download size={17} /></a></div><div className="experience-row reveal"><span className="experience-date">APR — JUN 2026</span><div><h3>Adobe <span>↗</span></h3><p>Technical Consultant Intern · Bengaluru</p></div><p>Strengthened front-end and responsive design skills through UI enablement training. Explored Edge Delivery Services and built a responsive e-commerce capstone with Adobe EDS.</p></div><div className="experience-row reveal"><span className="experience-date">2025 — 2027</span><div><h3>CHRIST University</h3><p>Master of Computer Applications</p></div><p>Expanding my foundations in software engineering. Also volunteered at Gateways, a national-level inter-collegiate IT fest.</p></div><div className="awards reveal"><span>MARKERS ALONG THE WAY</span><div><strong>Overall winner</strong><p>SHELLS’26 · National tech fest</p></div><div><strong>Top 30</strong><p>Karnataka II PUC · State rank, 2022</p></div></div></section>
  <section className="toolkit section-pad"><div className="section-label"><span>04 / THE TOOLKIT</span><span>THE RIGHT TOOL. THE RIGHT PROBLEM.</span></div><h2 className="reveal">Built across<br /><em>the stack.</em></h2><div className="skill-rows">{[["01", "Interface", "React.js / Next.js / Flutter / Tailwind CSS"], ["02", "Engineering", "TypeScript / JavaScript / Python / Go / Java / C/C++"], ["03", "Systems & data", "Node.js / Express.js / MongoDB / MySQL / Firebase"], ["04", "Delivery", "Docker / Git / GitHub / Adobe EDS"]].map(([id, label, skills]) => <div className="skill-row reveal" key={id}><span>{id}</span><h3>{label}</h3><p>{skills}</p><ArrowUpRight aria-hidden="true" /></div>)}</div></section>
  <footer id="contact" className="contact section-pad"><div className="section-label"><span>05 / WHAT’S NEXT?</span><a href="#home">BACK TO TOP ↑</a></div><p>Have a challenging problem or a role in mind?</p><a className="contact-title" href="mailto:Rajeev.chandar@mca.christuniversity.in">LET’S BUILD<br /><span>SOMETHING.</span><ArrowUpRight /></a><div className="contact-links"><a href="mailto:Rajeev.chandar@mca.christuniversity.in">Email me <ArrowUpRight size={18} /></a><button onClick={copyEmail} aria-live="polite">{copied ? "Email copied ✓" : "Copy email"}</button><a href="https://www.linkedin.com/in/a-r-rajeev-chandar-442141264/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={18} /></a><a href="/Rajeev-Chandar-Resume.pdf" download>Résumé <Download size={18} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} A R RAJEEV CHANDAR</span><span>BENGALURU, INDIA</span><span>MADE WITH INTENT.</span></div></footer>
  <Dialog open={detail !== null} onOpenChange={open => { if (!open) setDetail(null); }}><DialogContent className="project-dialog">{detail !== null && <><span className="eyebrow">{projects[detail].category} · {projects[detail].date}</span><DialogTitle className="dialog-title">{projects[detail].name}</DialogTitle><DialogDescription className="dialog-description">{projects[detail].detail}</DialogDescription><h4>How it comes together</h4><ol>{projects[detail].steps.map(step => <li key={step}>{step}</li>)}</ol><h4>Technology</h4><p>{projects[detail].stack}</p><a className="text-link" href={`mailto:Rajeev.chandar@mca.christuniversity.in?subject=${encodeURIComponent(`Let's talk about ${projects[detail].name}`)}`}>Discuss this project <ArrowUpRight size={16} /></a></>}</DialogContent></Dialog>
 </main>;
}
