"use client";
import { useState } from "react";
import { ArrowUpRight, Check, ChevronRight, Fingerprint, Layers, LockKeyhole, Mic, MoveUpRight, ScanLine, Sparkles, Upload, Wallet } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

function Waveform({ variant = 0 }: { variant?: number }) {
  return <div className="waveform" aria-hidden="true">{Array.from({ length: 43 }, (_, i) => <i key={i} style={{ height: `${Math.round(10 + Math.abs(Math.sin(i * 0.8 + variant) * Math.cos(i * 0.27)) * 90)}%`, animationDelay: `${(i * -0.067).toFixed(3)}s` }} />)}</div>;
}

export function SolenneDemo({ step }: { step: number }) {
  const [signal, setSignal] = useState("voice");
  return <div className="demo-rig solenne-rig" data-step={step}>
    <div className="float-chip chip-one"><span className="tiny-dot" />{step === 0 ? "A PRIVATE MOMENT" : step === 1 ? "SIGNALS, CONNECTED" : "READY TO REFLECT"}</div>
    <div className="app-window solenne-window"><div className="app-top"><span className="solenne-brand">solenne<span>✳</span></span><span className="app-avatar">R</span></div><div className="app-body"><span className="micro">YOUR DAILY SPACE</span><h4>{step === 0 ? <>Some things are<br />better said.</> : step === 1 ? <>A little more<br />understanding.</> : <>A moment.<br />A new perspective.</>}</h4><div className="journal-visual"><span className="journal-orbit orbit-one"/><span className="journal-orbit orbit-two"/><span className="journal-orbit orbit-three"/><div className="journal-core"><Mic size={26}/></div><span className="journal-time">{step === 0 ? "YOUR STORY STARTS HERE" : step === 1 ? "FINDING THE SIGNAL" : "REFLECTION, DELIVERED"}</span></div><Waveform variant={signal === "voice" ? 0 : signal === "speech" ? 2 : 4}/><Tabs value={signal} onValueChange={setSignal} className="signal-tabs"><TabsList aria-label="Explore Solenne signals"><TabsTrigger value="voice">Voice</TabsTrigger><TabsTrigger value="speech">Speech</TabsTrigger><TabsTrigger value="visual">Visual</TabsTrigger></TabsList></Tabs><p className="signal-explanation">{signal === "voice" ? "Tone, energy, pauses, and prosody." : signal === "speech" ? "Transcription turns speech into text." : "Quality-aware frame and face sampling."}</p><div className="app-action"><span>{step === 2 ? "Reflection ready" : step === 1 ? "Analysis pipeline" : "Video journal"}</span>{step === 2 ? <Check size={17}/> : <ArrowUpRight size={17}/>}</div></div><div className="app-bottom"><LockKeyhole size={11}/> NON-CLINICAL REFLECTION PROTOTYPE</div></div>
    <div className="floating-panel solenne-insight"><Sparkles size={18}/><span className="micro">{step === 2 ? "REFLECTION PROMPT" : "ONE CONNECTED PIPELINE"}</span><p>{step === 2 ? "What made you pause today?" : "Speech + voice + visual signals"}</p><div className="panel-line"/><span>{step === 2 ? "A gentle invitation to look inward." : "Processed in a background worker."}</span></div>
  </div>;
}

export function CortexDemo({ step }: { step: number }) {
  const [checked, setChecked] = useState(false);
  return <div className="demo-rig cortex-rig" data-step={step}><div className="float-chip chip-one"><span className="tiny-dot"/>CLASSROOM → CLARITY</div><div className="app-window cortex-window"><div className="app-top"><span className="cortex-brand"><Layers size={21}/> CortexEdu</span><span className="app-avatar">RC</span></div><div className="app-body"><span className="micro">ILLUSTRATIVE STUDENT VIEW</span><h4>A good day<br />to learn something.</h4><div className="class-banner"><span className="micro">YOUR CLASSROOM</span><h5>Software Engineering</h5><span>Interactive class · Faculty & students</span><div className="avatar-stack"><b>R</b><b>A</b><b>S</b><b>+</b></div></div><div className="class-panels"><div className="attendance-panel"><ScanLine size={24}/><span>Class check-in</span><strong>{checked ? "You're checked in" : "Ready when you are"}</strong><button onClick={() => setChecked(!checked)}>{checked ? "Reset demo" : "Try check-in"}{checked ? <Check size={14}/> : <ChevronRight size={14}/>}</button></div><div className="assessment-panel"><span className="micro">ASSESSMENT FLOW</span><div className="assessment-steps"><span className={step >= 0 ? "done" : ""}>Classwork</span><i/><span className={step >= 1 ? "done" : ""}>Calculate</span><i/><span className={step >= 2 ? "done" : ""}>Review</span></div></div></div><div className="reward-row"><span className="reward-icon">✳</span><div><strong>{step === 2 || checked ? "Participation recognized" : "Every contribution matters"}</strong><span>Student token reward system</span></div><MoveUpRight size={19}/></div></div></div><div className="floating-panel cortex-float"><span className="micro">LESS REPETITION</span><strong>More room<br />for learning.</strong><span>Classes. Attendance. Assessment.</span></div></div>;
}

export function DoChainDemo({ step }: { step: number }) {
  const [connected, setConnected] = useState(false);
  return <div className="demo-rig dochain-rig" data-step={step}><div className="float-chip chip-one"><span className="tiny-dot"/>A TRANSACTION YOU CAN TRACE</div><div className="app-window dochain-window"><div className="app-top"><span className="dochain-brand"><Fingerprint size={24}/> DoChain</span><span className="network-pill">POLYGON TESTNET</span></div><div className="app-body"><span className="micro">DOCUMENT TRANSACTION / DEMO</span><h4>Trust starts<br />with a clear trail.</h4><div className="document-visual"><div className="document-sheet"><span>DOC / 001</span><h5>document.pdf</h5><div/><div/><div/><b>{step === 2 ? <Check/> : <LockKeyhole/>}</b></div><div className="document-shadow"/></div><div className="chain-stages"><span className={step >= 0 ? "done" : ""}><Wallet size={15}/>Wallet</span><i/><span className={step >= 1 ? "done" : ""}><Upload size={15}/>IPFS</span><i/><span className={step >= 2 ? "done" : ""}><Layers size={15}/>Contract</span></div><button className="demo-primary" onClick={() => setConnected(!connected)}>{connected ? "Reset wallet simulation" : "Simulate wallet connection"}{connected ? <Check size={15}/> : <ArrowUpRight size={15}/>}</button><p className="demo-disclaimer">{connected ? "Demo identity connected. No wallet or signature requested." : "A local simulation. No wallet extension needed."}</p></div></div><div className="floating-panel chain-receipt"><span className="micro">{step === 2 ? "TRANSACTION FLOW" : "SEPARATION OF CONCERNS"}</span><div><span>Identity</span><strong>MetaMask</strong></div><div><span>File storage</span><strong>IPFS / Pinata</strong></div><div><span>Transaction</span><strong>Solidity</strong></div><p><Check size={13}/>{step === 2 ? "Conceptual flow complete" : "Files off-chain. Logic on-chain."}</p></div></div>;
}

export function FitnessDemo({ step }: { step: number }) {
  const [goal, setGoal] = useState("strength");
  const labels = goal === "strength" ? ["Movement focus", "Strength sessions", "Recovery blocks"] : goal === "endurance" ? ["Pacing focus", "Endurance sessions", "Recovery blocks"] : ["Movement variety", "Balanced sessions", "Recovery blocks"];
  return <div className="demo-rig fitness-rig" data-step={step}><div className="float-chip chip-one"><span className="tiny-dot"/>A PLAN THAT STARTS WITH YOU</div><div className="app-window fitness-window"><div className="app-top"><span className="fitness-brand">AI<span>FITNESS</span></span><Sparkles size={20}/></div><div className="app-body"><span className="micro">PERSONALIZED BY DESIGN</span><h4>Your starting point.<br />Your next step.</h4><Tabs value={goal} onValueChange={setGoal} className="goal-tabs"><TabsList aria-label="Preview a fitness goal"><TabsTrigger value="strength">Strength</TabsTrigger><TabsTrigger value="endurance">Endurance</TabsTrigger><TabsTrigger value="balance">Balance</TabsTrigger></TabsList></Tabs><div className="fitness-metric"><span>{goal === "strength" ? "BUILD" : goal === "endurance" ? "GO" : "FIND"}</span><strong>{goal === "strength" ? "STRONGER." : goal === "endurance" ? "FURTHER." : "BALANCE."}</strong><Waveform variant={goal === "strength" ? 0 : 2}/></div><div className="plan-preview"><span className="micro">{step < 2 ? "ILLUSTRATIVE PLAN STRUCTURE" : "A ROUTINE, ORGANIZED"}</span>{labels.map((label, i) => <div key={label}><span>0{i + 1}</span><strong>{label}</strong><ChevronRight size={15}/></div>)}</div><p className="demo-disclaimer">Preview only · No live AI call or exercise prescription.</p></div></div><div className="floating-panel fitness-float"><Sparkles size={17}/><span className="micro">CONTEXT → GENERATION</span><p>Individual inputs.<br />Personalized output.</p><span>Powered by Gemini in the project.</span></div></div>;
}
